export const programOptions = [
  { label: 'African, African American, and Diaspora Studies', value: 'african-african-american-and-diaspora-studies' },
  { label: 'American Studies', value: 'american-studies' },
  { label: 'Anthropology', value: 'anthropology' },
  { label: 'Applied Sciences', value: 'applied-sciences' },
  { label: 'Archaeology', value: 'archaeology' },
  { label: 'Art History', value: 'art-history' },
  { label: 'Asian Studies', value: 'asian-studies' },
  { label: 'Biology', value: 'biology' },
  { label: 'Biomedical Engineering', value: 'biomedical-engineering' },
  { label: 'Biostatistics', value: 'biostatistics' },
  { label: 'Business Administration', value: 'business-administration' },
  { label: 'Chemistry', value: 'chemistry' },
  { label: 'Classics', value: 'classics' },
  { label: 'Clinical Laboratory Science', value: 'clinical-laboratory-science' },
  { label: 'Communication Studies', value: 'communication-studies' },
  { label: 'Community and Global Public Health', value: 'community-and-global-public-health' },
  { label: 'Computer Science', value: 'computer-science' },
  { label: 'Contemporary European Studies', value: 'contemporary-european-studies' },
  { label: 'Data Science', value: 'data-science' },
  { label: 'Dental Hygiene', value: 'dental-hygiene' },
  { label: 'Doctor of Dental Surgery', value: 'doctor-of-dental-surgery' },
  { label: 'Doctor of Pharmacy', value: 'doctor-of-pharmacy' },
  { label: 'Dramatic Art', value: 'dramatic-art' },
  { label: 'Earth and Marine Sciences', value: 'earth-and-marine-sciences' },
  { label: 'Economics', value: 'economics' },
  { label: 'English and Comparative Literature', value: 'english-and-comparative-literature' },
  { label: 'Environmental Health Sciences', value: 'environmental-health-sciences' },
  { label: 'Environmental Science', value: 'environmental-science' },
  { label: 'Exercise and Sport Science', value: 'exercise-and-sport-science' },
  { label: 'Geography and Environment', value: 'geography-and-environment' },
  { label: 'Geological Sciences', value: 'geological-sciences' },
  { label: 'Germanic and Slavic Languages and Literatures', value: 'germanic-and-slavic-languages-and-literatures' },
  { label: 'Global Studies', value: 'global-studies' },
  { label: 'Health Policy and Management', value: 'health-policy-and-management' },
  { label: 'History', value: 'history' },
  { label: 'Human and Organizational Leadership Development', value: 'human-and-organizational-leadership-development' },
  { label: 'Human Development and Family Science', value: 'human-development-and-family-science' },
  { label: 'Information Science', value: 'information-science' },
  { label: 'Interdisciplinary Studies', value: 'interdisciplinary-studies' },
  { label: 'Latin American Studies', value: 'latin-american-studies' },
  { label: 'Linguistics', value: 'linguistics' },
  { label: 'Management and Society', value: 'management-and-society' },
  { label: 'Mathematics', value: 'mathematics' },
  { label: 'Media and Journalism', value: 'media-and-journalism' },
  { label: 'Medical Anthropology', value: 'medical-anthropology' },
  { label: 'Music', value: 'music' },
  { label: 'Neurodiagnostics and Sleep Science', value: 'neurodiagnostics-and-sleep-science' },
  { label: 'Neuroscience', value: 'neuroscience' },
  { label: 'Nursing', value: 'nursing' },
  { label: 'Nutrition', value: 'nutrition' },
  { label: 'Peace, War, and Defense', value: 'peace-war-and-defense' },
  { label: 'Philosophy', value: 'philosophy' },
  { label: 'Physics', value: 'physics' },
  { label: 'Political Science', value: 'political-science' },
  { label: 'Psychology', value: 'psychology' },
  { label: 'Public Policy', value: 'public-policy' },
  { label: 'Radiologic Science', value: 'radiologic-science' },
  { label: 'Religious Studies', value: 'religious-studies' },
  { label: 'Romance Languages', value: 'romance-languages' },
  { label: 'Sociology', value: 'sociology' },
  { label: 'Statistics and Analytics', value: 'statistics-and-analytics' },
  { label: 'Studio Art', value: 'studio-art' },
  { label: 'Women’s and Gender Studies', value: 'womens-and-gender-studies' },
]
