export const programOptions = [
  { label: 'Aerospace Studies Minor', value: 'aerospace-studies-minor' },
  { label: 'African American and Diaspora Studies Minor', value: 'african-american-and-diaspora-studies-minor' },
  { label: 'African Studies Minor', value: 'african-studies-minor' },
  { label: 'African, African American, and Diaspora Studies Major, B.A.', value: 'african-african-american-and-diaspora-studies-major-ba' },
  { label: 'American Indian and Indigenous Studies Minor', value: 'american-indian-and-indigenous-studies-minor' },
  { label: 'American Studies Major, B.A.', value: 'american-studies-major-ba' },
  { label: 'American Studies Major, B.A.–American Indian and Indigenous Studies Concentration', value: 'american-studies-major-ba-american-indian-and-indigenous-studies-concentration' },
  { label: 'American Studies Minor', value: 'american-studies-minor' },
  { label: 'Anthropology (General) Minor', value: 'anthropology-general-minor' },
  { label: 'Anthropology Major, B.A.', value: 'anthropology-major-ba' },
  { label: 'Applied Sciences and Engineering Minor', value: 'applied-sciences-and-engineering-minor' },
  { label: 'Applied Sciences, B.S.', value: 'applied-sciences-bs' },
  { label: 'Arabic Minor', value: 'arabic-minor' },
  { label: 'Archaeology Major, B.A.', value: 'archaeology-major-ba' },
  { label: 'Archaeology Minor', value: 'archaeology-minor' },
  { label: 'Art History Major, B.A.', value: 'art-history-major-ba' },
  { label: 'Art History Minor', value: 'art-history-minor' },
  { label: 'Asian Studies Major, B.A.–Arab Cultures Concentration', value: 'asian-studies-major-ba-arab-cultures-concentration' },
  { label: 'Asian Studies Major, B.A.–Chinese Concentration', value: 'asian-studies-major-ba-chinese-concentration' },
  { label: 'Asian Studies Major, B.A.–Interdisciplinary Concentration', value: 'asian-studies-major-ba-interdisciplinary-concentration' },
  { label: 'Asian Studies Major, B.A.–Japanese Concentration', value: 'asian-studies-major-ba-japanese-concentration' },
  { label: 'Asian Studies Major, B.A.–Korean Studies Concentration', value: 'asian-studies-major-ba-korean-studies-concentration' },
  { label: 'Asian Studies Major, B.A.–Persian Studies Concentration', value: 'asian-studies-major-ba-persian-studies-concentration' },
  { label: 'Asian Studies Major, B.A.–South Asian Studies Concentration', value: 'asian-studies-major-ba-south-asian-studies-concentration' },
  { label: 'Asian Studies Minor', value: 'asian-studies-minor' },
  { label: 'Astronomy Minor', value: 'astronomy-minor' },
  { label: 'Baccalaureate Education in Science and Teaching (BEST) Minor', value: 'baccalaureate-education-in-science-and-teaching-best-minor' },
  { label: 'Biology Major, B.A.', value: 'biology-major-ba' },
  { label: 'Biology Major, B.S.', value: 'biology-major-bs' },
  { label: 'Biology Major, B.S.–Quantitative Biology Track', value: 'biology-major-bs-quantitative-biology-track' },
  { label: 'Biology Minor', value: 'biology-minor' },
  { label: 'Biomedical Engineering Major, B.S.', value: 'biomedical-engineering-major-bs' },
  { label: 'Biostatistics Major, B.S.P.H.', value: 'biostatistics-major-bsph' },
  { label: 'Business Administration Major, B.S.B.A.', value: 'business-administration-major-bsb-a' },
  { label: 'Business Administration Minor', value: 'business-administration-minor' },
  { label: 'Business of Health Minor', value: 'business-of-health-minor' },
  { label: 'Chemistry Major, B.A.', value: 'chemistry-major-ba' },
  { label: 'Chemistry Major, B.S.', value: 'chemistry-major-bs' },
  { label: 'Chemistry Major, B.S.–Biochemistry Track', value: 'chemistry-major-bs-biochemistry-track' },
  { label: 'Chemistry Major, B.S.–Polymer Track', value: 'chemistry-major-bs-polymer-track' },
  { label: 'Chemistry Minor', value: 'chemistry-minor' },
  { label: 'Chinese Minor', value: 'chinese-minor' },
  { label: 'Civic Life and Leadership Minor', value: 'civic-life-and-leadership-minor' },
  { label: 'Classical Humanities Minor', value: 'classical-humanities-minor' },
  { label: 'Classics Major, B.A.–Classical Archaeology', value: 'classics-major-ba-classical-archaeology' },
  { label: 'Classics Major, B.A.–Classical Civilization', value: 'classics-major-ba-classical-civilization' },
  { label: 'Classics Major, B.A.–Greek, Latin, and Combined Greek and Latin', value: 'classics-major-ba-greek-latin-and-combined-greek-and-latin' },
  { label: 'Climate Change Minor', value: 'climate-change-minor' },
  { label: 'Clinical Laboratory Science Major, B.S.', value: 'clinical-laboratory-science-major-bs' },
  { label: 'Coaching Education Minor', value: 'coaching-education-minor' },
  { label: 'Communication Studies Major, B.A.', value: 'communication-studies-major-ba' },
  { label: 'Community and Global Public Health Major, B.S.P.H.', value: 'community-and-global-public-health-major-bsph' },
  { label: 'Comparative Literature Minor', value: 'comparative-literature-minor' },
  { label: 'Computer Science Major, B.A.', value: 'computer-science-major-ba' },
  { label: 'Computer Science Major, B.S.', value: 'computer-science-major-bs' },
  { label: 'Computer Science Minor', value: 'computer-science-minor' },
  { label: 'Conflict Management Minor', value: 'conflict-management-minor' },
  { label: 'Contemporary European Studies Major, B.A.', value: 'contemporary-european-studies-major-ba' },
  { label: 'Creative Writing Minor', value: 'creative-writing-minor' },
  { label: 'Data Science Major, B.A.', value: 'data-science-major-ba' },
  { label: 'Data Science Major, B.S.', value: 'data-science-major-bs' },
  { label: 'Data Science Minor', value: 'data-science-minor' },
  { label: 'Dental Hygiene Major, B.S.', value: 'dental-hygiene-major-bs' },
  { label: 'Doctor of Dental Surgery, D.D.S.', value: 'doctor-of-dental-surgery-dds' },
  { label: 'Doctor of Pharmacy (Pharm.D.)', value: 'doctor-of-pharmacy-pharmd' },
  { label: 'Dramatic Art Major, B.A.', value: 'dramatic-art-major-ba' },
  { label: 'Dramatic Art Minor', value: 'dramatic-art-minor' },
  { label: 'Earth and Marine Sciences Major, B.S.', value: 'earth-and-marine-sciences-major-bs' },
  { label: 'Economics Major, B.A.', value: 'economics-major-ba' },
  { label: 'Economics Major, B.S.', value: 'economics-major-bs' },
  { label: 'Economics Minor', value: 'economics-minor' },
  { label: 'Education Minor', value: 'education-minor' },
  { label: 'Engineering for Environmental Change, Climate, and Health Minor', value: 'engineering-for-environmental-change-climate-and-health-minor' },
  { label: 'English and Comparative Literature Major, B.A.', value: 'english-and-comparative-literature-major-ba' },
  { label: 'English Minor', value: 'english-minor' },
  { label: 'Entrepreneurship Minor', value: 'entrepreneurship-minor' },
  { label: 'Environmental Health Sciences Major, B.S.P.H.', value: 'environmental-health-sciences-major-bsph' },
  { label: 'Environmental Justice Minor', value: 'environmental-justice-minor' },
  { label: 'Environmental Microbiology Minor', value: 'environmental-microbiology-minor' },
  { label: 'Environmental Science and Studies Minor', value: 'environmental-science-and-studies-minor' },
  { label: 'Environmental Science Major, B.S.', value: 'environmental-science-major-bs' },
  { label: 'Environmental Studies Major, B.A.', value: 'environmental-studies-major-ba' },
  { label: 'Exercise and Sport Science Major, B.A.–Fitness Professional', value: 'exercise-and-sport-science-major-ba-fitness-professional' },
  { label: 'Exercise and Sport Science Major, B.A.–General', value: 'exercise-and-sport-science-major-ba-general' },
  { label: 'Exercise and Sport Science Major, B.A.–Sport Administration', value: 'exercise-and-sport-science-major-ba-sport-administration' },
  { label: 'Exercise and Sport Science Major, B.S.', value: 'exercise-and-sport-science-major-bs' },
  { label: 'Exercise and Sport Science Minor', value: 'exercise-and-sport-science-minor' },
  { label: 'Food Studies Minor', value: 'food-studies-minor' },
  { label: 'French Minor', value: 'french-minor' },
  { label: 'Geographic Information Sciences Minor', value: 'geographic-information-sciences-minor' },
  { label: 'Geography and Environment Major, B.A.', value: 'geography-and-environment-major-ba' },
  { label: 'Geography Minor', value: 'geography-minor' },
  { label: 'Geological Sciences Major, B.A.–Earth Science Concentration', value: 'geological-sciences-major-ba-earth-science-concentration' },
  { label: 'Geological Sciences Minor', value: 'geological-sciences-minor' },
  { label: 'German Studies Minor', value: 'german-studies-minor' },
  { label: 'Germanic and Slavic Languages and Literatures Major, B.A.–German Studies Concentration', value: 'germanic-and-slavic-languages-and-literatures-major-ba-german-studies-concentration' },
  { label: 'Germanic and Slavic Languages and Literatures Major, B.A.–Russian Language and Culture Concentration', value: 'germanic-and-slavic-languages-and-literatures-major-ba-russian-language-and-culture-concentration' },
  { label: 'Germanic and Slavic Languages and Literatures Major, B.A.–Slavic and East European Studies Concentration', value: 'germanic-and-slavic-languages-and-literatures-major-ba-slavic-and-east-european-studies-concentration' },
  { label: 'Global Cinema Minor', value: 'global-cinema-minor' },
  { label: 'Global Studies Major, B.A.', value: 'global-studies-major-ba' },
  { label: 'Greek Minor', value: 'greek-minor' },
  { label: 'Health and Society Minor', value: 'health-and-society-minor' },
  { label: 'Health Policy and Management Major, B.S.P.H.', value: 'health-policy-and-management-major-bsph' },
  { label: 'Heritage and Global Engagement Minor', value: 'heritage-and-global-engagement-minor' },
  { label: 'Hindi-Urdu Minor', value: 'hindi-urdu-minor' },
  { label: 'Hispanic Studies Minor', value: 'hispanic-studies-minor' },
  { label: 'History Major, B.A.', value: 'history-major-ba' },
  { label: 'History Minor', value: 'history-minor' },
  { label: 'Human and Organizational Leadership Development Major, B.A.', value: 'human-and-organizational-leadership-development-major-ba' },
  { label: 'Human Development and Family Science Major, B.A.Ed.', value: 'human-development-and-family-science-major-baed' },
  { label: 'Human Development, Sustainability, and Rights in Africa and the African Diaspora Minor', value: 'human-development-sustainability-and-rights-in-africa-and-the-african-diaspora-minor' },
  { label: 'Hydrology Minor', value: 'hydrology-minor' },
  { label: 'Information Science Major, B.S.', value: 'information-science-major-bs' },
  { label: 'Information Systems Minor', value: 'information-systems-minor' },
  { label: 'Interdisciplinary Studies Major, B.A.', value: 'interdisciplinary-studies-major-ba' },
  { label: 'Islamic and Middle Eastern Studies Minor', value: 'islamic-and-middle-eastern-studies-minor' },
  { label: 'Italian Minor', value: 'italian-minor' },
  { label: 'Japanese Minor', value: 'japanese-minor' },
  { label: 'Jewish Studies Minor', value: 'jewish-studies-minor' },
  { label: 'Korean Minor', value: 'korean-minor' },
  { label: 'Latin American Studies Major, B.A.', value: 'latin-american-studies-major-ba' },
  { label: 'Latin Minor', value: 'latin-minor' },
  { label: 'Latina/o Studies Minor', value: 'latina-o-studies-minor' },
  { label: 'Linguistics Major, B.A.', value: 'linguistics-major-ba' },
  { label: 'Linguistics Minor', value: 'linguistics-minor' },
  { label: 'Management and Society Major, B.A.', value: 'management-and-society-major-ba' },
  { label: 'Marine Sciences Minor', value: 'marine-sciences-minor' },
  { label: 'Mathematics Major, B.A.', value: 'mathematics-major-ba' },
  { label: 'Mathematics Major, B.S.', value: 'mathematics-major-bs' },
  { label: 'Mathematics Minor', value: 'mathematics-minor' },
  { label: 'Media and Journalism Major, B.A.', value: 'media-and-journalism-major-ba' },
  { label: 'Media and Journalism Minor', value: 'media-and-journalism-minor' },
  { label: 'Medical Anthropology Major, B.A.', value: 'medical-anthropology-major-ba' },
  { label: 'Medical Anthropology Minor', value: 'medical-anthropology-minor' },
  { label: 'Medicine, Literature, and Culture Minor', value: 'medicine-literature-and-culture-minor' },
  { label: 'Medieval and Early Modern Studies (MEMS) Minor', value: 'medieval-and-early-modern-studies-mems-minor' },
  { label: 'Middle Eastern Languages Minor', value: 'middle-eastern-languages-minor' },
  { label: 'Military Science and Leadership Minor', value: 'military-science-and-leadership-minor' },
  { label: 'Modern Hebrew Minor', value: 'modern-hebrew-minor' },
  { label: 'Music Major, B.A.', value: 'music-major-ba' },
  { label: 'Music Major, Bachelor of Music (B.Mus.)', value: 'music-major-bachelor-of-music-bmus' },
  { label: 'Music Minor', value: 'music-minor' },
  { label: 'Musical Theatre Performance Minor', value: 'musical-theatre-performance-minor' },
  { label: 'Naval Science Minor', value: 'naval-science-minor' },
  { label: 'Neurodiagnostics and Sleep Science Major, B.S.', value: 'neurodiagnostics-and-sleep-science-major-bs' },
  { label: 'Neuroscience Major, B.S.', value: 'neuroscience-major-bs' },
  { label: 'Neuroscience Minor', value: 'neuroscience-minor' },
  { label: 'Nursing Major, B.S.N.', value: 'nursing-major-bsn' },
  { label: 'Nutrition Major, B.S.P.H.', value: 'nutrition-major-bsph' },
  { label: 'Peace, War, and Defense Major, B.A.', value: 'peace-war-and-defense-major-ba' },
  { label: 'Persian Minor', value: 'persian-minor' },
  { label: 'Pharmaceutical Sciences Minor', value: 'pharmaceutical-sciences-minor' },
  { label: 'Philosophy Major, B.A.', value: 'philosophy-major-ba' },
  { label: 'Philosophy Minor', value: 'philosophy-minor' },
  { label: 'Philosophy, Politics, and Economics (PPE) Minor', value: 'philosophy-politics-and-economics-ppe-minor' },
  { label: 'Physics Major, B.A.', value: 'physics-major-ba' },
  { label: 'Physics Major, B.S.', value: 'physics-major-bs' },
  { label: 'Physics Minor', value: 'physics-minor' },
  { label: 'Political Science Major, B.A.', value: 'political-science-major-ba' },
  { label: 'Portuguese Minor', value: 'portuguese-minor' },
  { label: 'Psychology Major, B.A.', value: 'psychology-major-ba' },
  { label: 'Psychology Major, B.S.', value: 'psychology-major-bs' },
  { label: 'Public Policy Major, B.A.', value: 'public-policy-major-ba' },
  { label: 'Public Policy Minor', value: 'public-policy-minor' },
  { label: 'Radiologic Science Major, B.S.', value: 'radiologic-science-major-bs' },
  { label: 'Real Estate Minor', value: 'real-estate-minor' },
  { label: 'Religious Studies Major, B.A.', value: 'religious-studies-major-ba' },
  { label: 'Religious Studies Major, B.A.–Jewish Studies Concentration', value: 'religious-studies-major-ba-jewish-studies-concentration' },
  { label: 'Religious Studies Minor', value: 'religious-studies-minor' },
  { label: 'Risk Management Minor', value: 'risk-management-minor' },
  { label: 'Romance Languages Major, B.A.–French and Francophone Studies', value: 'romance-languages-major-ba-french-and-francophone-studies' },
  { label: 'Romance Languages Major, B.A.–Hispanic Linguistics', value: 'romance-languages-major-ba-hispanic-linguistics' },
  { label: 'Romance Languages Major, B.A.–Hispanic Studies', value: 'romance-languages-major-ba-hispanic-studies' },
  { label: 'Romance Languages Major, B.A.–Italian', value: 'romance-languages-major-ba-italian' },
  { label: 'Romance Languages Major, B.A.–Portuguese', value: 'romance-languages-major-ba-portuguese' },
  { label: 'Russian Culture Minor', value: 'russian-culture-minor' },
  { label: 'Screenwriting Minor', value: 'screenwriting-minor' },
  { label: 'Sexuality Studies Minor', value: 'sexuality-studies-minor' },
  { label: 'Slavic and East European Studies Minor', value: 'slavic-and-east-european-studies-minor' },
  { label: 'Social and Economic Justice Minor', value: 'social-and-economic-justice-minor' },
  { label: 'Sociology Major, B.A.', value: 'sociology-major-ba' },
  { label: 'Southeast Asian Studies Minor', value: 'southeast-asian-studies-minor' },
  { label: 'Spanish Minor for the Professions', value: 'spanish-minor-for-the-professions' },
  { label: 'Speech and Hearing Sciences Minor', value: 'speech-and-hearing-sciences-minor' },
  { label: 'Sports Medicine Minor', value: 'sports-medicine-minor' },
  { label: 'Statistics and Analytics Major, B.S.', value: 'statistics-and-analytics-major-bs' },
  { label: 'Statistics and Analytics Minor', value: 'statistics-and-analytics-minor' },
  { label: 'Studio Art Major, B.A.', value: 'studio-art-major-ba' },
  { label: 'Studio Art Major, Bachelor of Fine Arts (B.F.A)', value: 'studio-art-major-bachelor-of-fine-arts-bfa' },
  { label: 'Studio Art Minor', value: 'studio-art-minor' },
  { label: 'Study of Christianity and Culture Minor', value: 'study-of-christianity-and-culture-minor' },
  { label: 'Sustainability Studies Minor', value: 'sustainability-studies-minor' },
  { label: 'Translation and Interpreting Minor', value: 'translation-and-interpreting-minor' },
  { label: 'Urban Studies and Planning Minor', value: 'urban-studies-and-planning-minor' },
  { label: 'Women’s and Gender Studies Major, B.A.', value: 'womens-and-gender-studies-major-ba' },
  { label: 'Women’s and Gender Studies Minor', value: 'womens-and-gender-studies-minor' },
  { label: 'Writing, Editing, and Digital Publishing Minor', value: 'writing-editing-and-digital-publishing-minor' },
]
